language: go

go:
  - 1.6

before_install:
  - go get github.com/stretchr/testify
  - go get github.com/PuerkitoBio/goquery

script:
  - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
