language: node_js

node_js:
  - 6.2.2

before_install:
  - npm install -g codecov
  - npm install -g istanbul
  - npm install

script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
  - codecov
